thm_bg="#32302F"
thm_fg="#D4BE98"

thm_border="#928374"
thm_text_highlight="#7daea3"
thm_text_dim="#7c6f64"

thm_bright_black="#45403d"
thm_blue="#7daea3"
thm_cyan="#89b482"
thm_green="#a9b665"
thm_red="#ea6962"
thm_magenta="#d3869b"
thm_yellow="#d8a657"
thm_orange="#e78a4e"
