thm_bg="#111c18"
thm_fg="#c1c497"

thm_border="#509475"
thm_text_highlight="#ff5345"
thm_text_dim="#53685b"

thm_bright_black="#53685b"
thm_blue="#509475"
thm_cyan="#8cd3cb"
thm_green="#63b07a"
thm_red="#ff5345"
thm_magenta="#d2689c"
thm_yellow="#dfa000"
thm_orange="#dfa000"
