font_family       CaskaydiaMono Nerd Font Regular
bold_font         CaskaydiaMono Nerd Font Bold
italic_font       CaskaydiaMono Nerd Font Italic
bold_italic_font  CaskaydiaMono Nerd Font Bold Italic
font_size         9.0
symbol_map        U+0E00-U+0E7F Noto Sans Thai Looped

opacity                 0.95
window_padding_width    10
hide_window_decorations yes
confirm_os_window_close 0

clipboard_control write-clipboard write-primary read-clipboard read-primary

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+p paste_from_clipboard

include themes/gruvbox-material.conf
