# This is default and very simple configuration file for Yasb.
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        - "home"
        - "glazewm_workspaces"
      center:
        - "clock"
      right:
        - "notifications"
        - "glazewm_tiling_direction"
        - "vpn"
        - "wifi"
        - "language"
        - "microphone"
        - "volume"
        - "cpu"
        - "memory"
        - "battery"
        - "power_menu"
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "~\\Downloads" }
        - { title: "Documents", path: "~\\Documents" }
        - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: false

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%A %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
      calendar:
        blur: false
        round_corners: false
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"

  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}%"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% | {power}W | {time_remaining}"
      update_interval: 5000
      time_remaining_natural: False
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 500
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "\uf0e7"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[freq][current]} MHz"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_menu"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
      menu:
        enabled: true
        show_graph: true
        show_graph_grid: true
        graph_history_size: 60

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_free}/{virtual_mem_total}"
      label_alt: "<span>\uefc5</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
      menu:
        enabled: true
        show_graph: true
        show_graph_grid: true
        graph_history_size: 60

  vpn:
    type: "yasb.custom.CustomWidget"
    options:
      label: "{data[icon]}<span>\uf48b</span>"
      tooltip: true
      tooltip_label: "VPN {data[connection]}"
      class_name: "vpn-widget"
      exec_options:
        run_cmd: "%USERPROFILE%\\.config\\yasb\\scripts\\vpn.cmd"
        run_interval: 5000
        return_format: "json"
      callbacks:
        on_left: "exec cmd /c \"C:\\Program Files (x86)\\Cisco\\Cisco Secure Client\\UI\\csc_ui.exe\""

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_name}"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: false # Optional. Will require location access permission if true.
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-24% strength
          "\udb82\udd22", # Icon for 25-49% strength
          "\udb82\udd25", # Icon for 50-74% strength
          "\udb82\udd28", # Icon for 75-100% strength
        ]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: ["\ue670", "\ue671", "\ue672", "\ue673"]
        wifi_icons_unsecured: ["\uec3c", "\uec3d", "\uec3e", "\uec3f"]

  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\udb80\udf0c</span> {lang[language_code]}-{lang[country_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 1
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      enable_scroll_switching: true
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 16
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
      animation: false
