set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-kitty:RGB"

run-shell "~/.config/tmux/scripts/bootstrap-theme.sh"

# nvim yank compatibility
set -s set-clipboard on
setw -g mode-keys vi

unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi y send-keys -X copy-pipe

# Key binding
bind r source-file $HOME/.config/tmux/tmux.conf

bind x kill-pane

bind C-b display-popup -w 40% -h 80% -b none "btop"

bind C-t display-popup -d "#{pane_current_path}" -E "bash"

bind T display-popup -E -w 60% -h 50% -b none \
  "bash ~/.config/tmux/scripts/theme-picker.sh"

# Navigation
bind -n S-Left previous-window
bind -n S-Right next-window

# Window & pane index
set -g base-index 1
setw -g pane-base-index 1

set -g status "on"
set -gF status-bg "#{@thm_bg}"

set -g pane-border-style "fg=#{@thm_bright_black}"
set -g pane-active-border-style "fg=#{@thm_blue}"

set -g popup-border-style "fg=#{@thm_border}"

# Status bar - OS info
run-shell 'tmux set-environment -g os_name "$(grep "^ID=" /etc/os-release | cut -d= -f2-)"'

%if "#{==:#{os_name},darwin}"
    set -g @os_icon ""
%elif "#{==:#{os_name},ubuntu}"
    set -g @os_icon ""
%elif "#{==:#{os_name},nixos}"
    set -g @os_icon ""
%else
    set -g @os_icon "󰌽"
%endif

# Status bar - window status
set -g window-status-activity-style "fg=#{@thm_fg},bg=#{@thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=#{@thm_fg},bg=#{@thm_bg},none"

set -g message-style "fg=#{@thm_cyan},bg=#{@thm_bright_black},align=centre"
set -g message-command-style "fg=#{@thm_cyan},bg=#{@thm_bright_black},align=centre"

# Status bar - window status format
set -g window-status-current-format "#[fg=#{@thm_text_highlight},bg=#{@thm_bg}] #I: #[fg=#{@thm_text_highlight},bg=#{@thm_bg}]() #[fg=#{@thm_text_highlight},bg=#{@thm_bg}]#W #[fg=#{@thm_magenta},bg=#{@thm_bg}]"
set -g window-status-format "#[fg=#{@thm_text_highlight},bg=#{@thm_bg}] #I: #[fg=#{@thm_text_dim},bg=#{@thm_bg}]#W"

# Status bar - status format
session_logic="#[fg=#{@thm_yellow}]#[bg=#{@thm_bg}]#[fg=#{@thm_bg}]#[bg=#{@thm_yellow}] #[fg=#{@thm_fg}]#[bg=#{@thm_bright_black}] "

distro_logic="#{?client_prefix,\
  #[fg=#{@thm_magenta}]#[bg=#{@thm_bright_black}]#[bg=#{@thm_magenta}]#[fg=#{@thm_bg}]#{@os_icon} #[fg=#{@thm_bg}]#[bg=#{@thm_magenta}] ,\
  #[fg=#{@thm_cyan}]#[bg=#{@thm_bright_black}]#[bg=#{@thm_cyan}]#[fg=#{@thm_bg}]#{@os_icon} #[fg=#{@thm_fg}]#[bg=#{@thm_bright_black}] }"

set -g status-right "${session_logic}#S${distro_logic}#{os_name} "

set -g status-left "#[fg=#{@thm_bg},bg=#{@thm_blue}]  #[fg=#{@thm_blue},bg=#{@thm_bg}]"
