set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

bind r source-file $HOME/.config/tmux/tmux.conf

bind x kill-pane

# Display popup
bind C-b display-popup -w 40% -h 80% "btop"
bind C-t display-popup -d "#{pane_current_path}" -E "bash -c 'if [ -f devbox.json ]; then devbox shell; else bash; fi'"

# Navigation
bind -n S-Left previous-window
bind -n S-Right next-window

# Window & pane index
set -g base-index 1
setw -g pane-base-index 1

# Themes
thm_bg="#111c18"
thm_fg="#c1c497"
thm_bright_black="#53685b"
thm_blue="#509475"
thm_cyan="#8cd3cb"
thm_green="#63b07a"
thm_red="#ff5345"
thm_magenta="#d2689c"

set -g status "on"
set -g status-bg "${thm_bg}"

set -g pane-border-style "fg=${thm_bright_black}"
set -g pane-active-border-style "fg=${thm_blue}"

# Themes - window status
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

set -g message-style "fg=${thm_cyan},bg=${thm_bright_black},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_bright_black},align=centre"

# Themes - window status format
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_red},bg=${thm_bg}]() #[fg=${thm_red},bg=${thm_bg}]#W #[fg=${thm_magenta},bg=${thm_bg}]"
set -g window-status-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_bright_black},bg=${thm_bg}]#W"

# Themes - status format
window_logic="#{?#{m/i:devbox*,#W},\
#[fg=${thm_green}]#[bg=${thm_bg}]#[fg=${thm_bg}]#[bg=${thm_green}] 󰋙 #[fg=${thm_fg}]#[bg=${thm_bright_black}] ,\
#[fg=${thm_blue}]#[bg=${thm_bg}]#[fg=${thm_bg}]#[bg=${thm_blue}]  #[fg=${thm_fg}]#[bg=${thm_bright_black}] }"

session_logic="#{?client_prefix,\
#[fg=${thm_magenta}]#[bg=${thm_bright_black}]#[bg=${thm_magenta}]#[fg=${thm_bg}]  #[fg=${thm_bg}]#[bg=${thm_magenta}] ,\
#[fg=${thm_cyan}]#[bg=${thm_bright_black}]#[bg=${thm_cyan}]#[fg=${thm_bg}]  #[fg=${thm_fg}]#[bg=${thm_bright_black}] }"

set -g status-right "${window_logic}#W ${session_logic}#S "

set -g status-left "#[fg=${thm_bg},bg=${thm_blue}]  #[fg=${thm_blue},bg=${thm_bg}]"
