theme[main_bg]="#32302f"

# Main text color
theme[main_fg]="#d4be98"

# Title color for boxes
theme[title]="#ebdbb2"

# Higlight color for keyboard shortcuts
theme[hi_fg]="#e78a4e"

# Background color of selected items
theme[selected_bg]="#d4be98"

# Foreground color of selected items
theme[selected_fg]="#32302f"

# Color of inactive/disabled text
theme[inactive_fg]="#282626"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#928374"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a9b665"

# Cpu box outline color
theme[cpu_box]="#928374"

# Memory/disks box outline color
theme[mem_box]="#928374"

# Net up/down box outline color
theme[net_box]="#928374"

# Processes box outline color
theme[proc_box]="#928374"

# Box divider line and small boxes line color
theme[div_line]="#928374"

# Temperature graph colors
theme[temp_start]="#7daea3"
theme[temp_mid]="#d3869b"
theme[temp_end]="#fb4394"

# CPU graph colors

theme[cpu_start]="#a9b665"
theme[cpu_mid]="#e78a4e"
theme[cpu_end]="#ea6962"

# Mem/Disk free meter
theme[free_start]="#4e5900"
theme[free_mid]=""
theme[free_end]="#98971a"

# Mem/Disk cached meter
theme[cached_start]="#458588"
theme[cached_mid]=""
theme[cached_end]="#7daea3"

# Mem/Disk available meter
theme[available_start]="#e78a4e"
theme[available_mid]=""
theme[available_end]="#d8a657"

# Mem/Disk used meter
theme[used_start]="#cc241d"
theme[used_mid]=""
theme[used_end]="#ea6962"

# Download graph colors
theme[download_start]="#3d4070"
theme[download_mid]="#6c71c4"
theme[download_end]="#a3a8f7"

# Upload graph colors
theme[upload_start]="#701c45"
theme[upload_mid]="#b16286"
theme[upload_end]="#d3869b"
